services:
  kfs-etcd:
    container_name: kfs-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      ETCD_NAME: "etcd-server"
      ETCD_INITIAL_CLUSTER: "etcd-server=http://0.0.0.0:2380"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - 2379:2379
      - 2380:2380
